/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  titulo?: string
  slug?: Slug
  categoria?: 'lifestyle-rj' | 'serra-gaucha' | 'mercado' | 'arquitetura'
  imagemCapa?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  resumo?: string
  conteudo?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        legenda?: string
        _type: 'image'
        _key: string
      }
  >
  bairroRelacionado?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'bairro'
  }
  autor?: string
  publicadoEm?: string
  destaque?: boolean
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type Imovel = {
  _id: string
  _type: 'imovel'
  _createdAt: string
  _updatedAt: string
  _rev: string
  titulo?: string
  slug?: Slug
  tipo?:
    | 'Apartamento'
    | 'Cobertura'
    | 'Cobertura Duplex'
    | 'Penthouse'
    | 'Casa'
    | 'Casa de Condom\xEDnio'
    | 'Terreno'
    | 'Loja'
    | 'Sala Comercial'
  finalidade?: 'Venda' | 'Loca\xE7\xE3o' | 'Temporada'
  mercado?: 'Rio de Janeiro' | 'Gramado' | 'Canela'
  status?: 'Dispon\xEDvel' | 'Em negocia\xE7\xE3o' | 'Vendido' | 'Locado' | 'Fora do mercado'
  destaque?: boolean
  exclusivo?: boolean
  permuta?: boolean
  novidade?: boolean
  precoSobConsulta?: boolean
  condominioRef?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'condominio'
  }
  publicadoEm?: string
  preco?: number
  condominio?: number
  iptu?: number
  areaUtil?: number
  areaTotal?: number
  quartos?: number
  suites?: number
  banheiros?: number
  vagas?: number
  andar?: string
  bairro?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'bairro'
  }
  endereco?: {
    logradouro?: string
    lat?: number
    lng?: number
  }
  imagens?: Array<{
    arquivo?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    alt?: string
    principal?: boolean
    tour360?: boolean
    urlMatterport?: string
    isStaging?: boolean
    stagingPar?: string
    _key: string
  }>
  plantas?: Array<{
    arquivo?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    titulo?: string
    ambientes?: Array<{
      nome?: string
      tipo?: 'coberto' | 'descoberto' | 'pergolado' | 'terra\xE7o' | 'piscina'
      area?: number
      x?: number
      y?: number
      _key: string
    }>
    _key: string
  }>
  caracteristicas?: Array<{
    grupo?: 'Lazer' | 'Seguran\xE7a' | 'Acabamento' | 'Vista' | 'Arquitetura' | 'Infraestrutura'
    nome?: string
    _key: string
  }>
  descricaoPtBr?: string
  descricaoEnUs?: string
  descricaoFrFr?: string
  seo?: {
    metaTitle?: string
    metaDescription?: string
  }
}

export type Condominio = {
  _id: string
  _type: 'condominio'
  _createdAt: string
  _updatedAt: string
  _rev: string
  nome?: string
  slug?: Slug
  bairro?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'bairro'
  }
  tipo?: 'condominio-fechado' | 'bairro-planejado' | 'vertical' | 'resort'
  destaque?: boolean
  fotoCapa?: {
    asset?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    alt?: string
  }
  galeria?: Array<{
    asset?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    alt?: string
    legenda?: string
    _key: string
  }>
  descricao?: string
  infraestrutura?: Array<string>
  areaTotal?: number
  totalLotes?: number
  geo?: {
    lat?: number
    lng?: number
  }
  ordem?: number
  seo?: {
    titulo?: string
    descricao?: string
  }
}

export type Bairro = {
  _id: string
  _type: 'bairro'
  _createdAt: string
  _updatedAt: string
  _rev: string
  nome?: string
  slug?: Slug
  cidade?: string
  estado?: 'RJ' | 'RS'
  mercado?: 'Rio de Janeiro' | 'Serra Ga\xFAcha'
  fotoCapa?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  fotoAerea?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  descricao?: string
  geo?: {
    lat?: number
    lng?: number
  }
  pontosDeInteresse?: Array<{
    nome?: string
    categoria?:
      | 'Praia'
      | 'Restaurante'
      | 'Shopping'
      | 'Escola'
      | 'Hospital'
      | 'Metr\xF4'
      | 'Supermercado'
      | 'Academia'
    lat?: number
    lng?: number
    _key: string
  }>
  regiao?: 'Centro' | 'Zona Sul' | 'Sudoeste' | 'Gramado' | 'Canela'
  ordem?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | BlogPost
  | Imovel
  | Condominio
  | Bairro
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/queries.ts
// Variable: imagemFragment
// Query: arquivo {    asset->{ _id, url, metadata { lqip, dimensions } },    hotspot, crop,    alt, principal, tour360, urlMatterport, isStaging, stagingPar  }
export type ImagemFragmentResult = never
// Variable: bairroFragment
// Query: bairro->{ _id, nome, slug, cidade, estado, mercado }
export type BairroFragmentResult = never
// Variable: IMOVEIS_CARD_QUERY
// Query: *[_type == "imovel" && status == "Disponível"] | order(publicadoEm desc) {    _id, titulo, slug, tipo, finalidade, mercado, status, destaque,    exclusivo, permuta, novidade, precoSobConsulta,    preco, areaUtil, quartos, suites, vagas, andar,      bairro->{ _id, nome, slug, cidade, estado, mercado },    "condominionome": condominioRef->nome,    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {      asset->{ _id, url, metadata { lqip, dimensions } },      hotspot, crop, alt    }  }
export type IMOVEIS_CARD_QUERYResult = Array<{
  _id: string
  titulo: string | null
  slug: Slug | null
  tipo:
    | 'Apartamento'
    | 'Casa de Condom\xEDnio'
    | 'Casa'
    | 'Cobertura Duplex'
    | 'Cobertura'
    | 'Loja'
    | 'Penthouse'
    | 'Sala Comercial'
    | 'Terreno'
    | null
  finalidade: 'Loca\xE7\xE3o' | 'Temporada' | 'Venda' | null
  mercado: 'Canela' | 'Gramado' | 'Rio de Janeiro' | null
  status: 'Dispon\xEDvel'
  destaque: boolean | null
  exclusivo: boolean | null
  permuta: boolean | null
  novidade: boolean | null
  precoSobConsulta: boolean | null
  preco: number | null
  areaUtil: number | null
  quartos: number | null
  suites: number | null
  vagas: number | null
  andar: string | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  condominionome: string | null
  imagemCapa: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: null
  } | null
}>
// Variable: IMOVEIS_FILTRADOS_QUERY
// Query: *[    _type == "imovel"    && status == "Disponível"    && ($tipo == "" || tipo == $tipo)    && ($mercado == "" || mercado == $mercado)    && ($finalidade == "" || finalidade == $finalidade)    && ($bairroSlug == "" || bairro->slug.current == $bairroSlug)    && ($precoMin == 0 || preco >= $precoMin)    && ($precoMax == 0 || preco <= $precoMax)    && ($quartos == 0 || quartos >= $quartos)  ] | order(publicadoEm desc) [$offset...$end] {    _id, titulo, slug, tipo, finalidade, mercado, status,    exclusivo, permuta, novidade, precoSobConsulta,    preco, areaUtil, quartos, suites, vagas, andar,      bairro->{ _id, nome, slug, cidade, estado, mercado },    "condominionome": condominioRef->nome,    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {      asset->{ _id, url, metadata { lqip, dimensions } },      hotspot, crop, alt    }  }
export type IMOVEIS_FILTRADOS_QUERYResult = Array<{
  _id: string
  titulo: string | null
  slug: Slug | null
  tipo:
    | 'Apartamento'
    | 'Casa de Condom\xEDnio'
    | 'Casa'
    | 'Cobertura Duplex'
    | 'Cobertura'
    | 'Loja'
    | 'Penthouse'
    | 'Sala Comercial'
    | 'Terreno'
    | null
  finalidade: 'Loca\xE7\xE3o' | 'Temporada' | 'Venda' | null
  mercado: 'Canela' | 'Gramado' | 'Rio de Janeiro' | null
  status: 'Dispon\xEDvel' | 'Em negocia\xE7\xE3o' | 'Fora do mercado' | 'Locado' | 'Vendido' | null
  exclusivo: boolean | null
  permuta: boolean | null
  novidade: boolean | null
  precoSobConsulta: boolean | null
  preco: number | null
  areaUtil: number | null
  quartos: number | null
  suites: number | null
  vagas: number | null
  andar: string | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  condominionome: string | null
  imagemCapa: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: null
  } | null
}>
// Variable: IMOVEL_PDI_QUERY
// Query: *[_type == "imovel" && slug.current == $slug][0] {    _id, titulo, slug, tipo, finalidade, mercado, status, destaque,    preco, condominio, iptu, areaUtil, areaTotal,    quartos, suites, banheiros, vagas, andar,      bairro->{ _id, nome, slug, cidade, estado, mercado },    endereco,    imagens[] {   arquivo {    asset->{ _id, url, metadata { lqip, dimensions } },    hotspot, crop,    alt, principal, tour360, urlMatterport, isStaging, stagingPar  } },    plantas[] {      arquivo { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },      titulo,      ambientes[] { nome, tipo, area, x, y }    },    caracteristicas[] { grupo, nome },    descricaoPtBr, descricaoEnUs, descricaoFrFr,    seo, publicadoEm  }
export type IMOVEL_PDI_QUERYResult = {
  _id: string
  titulo: string | null
  slug: Slug | null
  tipo:
    | 'Apartamento'
    | 'Casa de Condom\xEDnio'
    | 'Casa'
    | 'Cobertura Duplex'
    | 'Cobertura'
    | 'Loja'
    | 'Penthouse'
    | 'Sala Comercial'
    | 'Terreno'
    | null
  finalidade: 'Loca\xE7\xE3o' | 'Temporada' | 'Venda' | null
  mercado: 'Canela' | 'Gramado' | 'Rio de Janeiro' | null
  status: 'Dispon\xEDvel' | 'Em negocia\xE7\xE3o' | 'Fora do mercado' | 'Locado' | 'Vendido' | null
  destaque: boolean | null
  preco: number | null
  condominio: number | null
  iptu: number | null
  areaUtil: number | null
  areaTotal: number | null
  quartos: number | null
  suites: number | null
  banheiros: number | null
  vagas: number | null
  andar: string | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  endereco: {
    logradouro?: string
    lat?: number
    lng?: number
  } | null
  imagens: Array<{
    arquivo: {
      asset: {
        _id: string
        url: string | null
        metadata: {
          lqip: string | null
          dimensions: SanityImageDimensions | null
        } | null
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      alt: null
      principal: null
      tour360: null
      urlMatterport: null
      isStaging: null
      stagingPar: null
    } | null
  }> | null
  plantas: Array<{
    arquivo: {
      asset: {
        _id: string
        url: string | null
        metadata: {
          lqip: string | null
          dimensions: SanityImageDimensions | null
        } | null
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    } | null
    titulo: string | null
    ambientes: Array<{
      nome: string | null
      tipo: 'coberto' | 'descoberto' | 'pergolado' | 'piscina' | 'terra\xE7o' | null
      area: number | null
      x: number | null
      y: number | null
    }> | null
  }> | null
  caracteristicas: Array<{
    grupo:
      | 'Acabamento'
      | 'Arquitetura'
      | 'Infraestrutura'
      | 'Lazer'
      | 'Seguran\xE7a'
      | 'Vista'
      | null
    nome: string | null
  }> | null
  descricaoPtBr: string | null
  descricaoEnUs: string | null
  descricaoFrFr: string | null
  seo: {
    metaTitle?: string
    metaDescription?: string
  } | null
  publicadoEm: string | null
} | null
// Variable: IMOVEIS_DESTAQUE_QUERY
// Query: *[_type == "imovel" && destaque == true && status == "Disponível"] | order(publicadoEm desc)[0...6] {    _id, titulo, slug, tipo, finalidade, mercado, preco, areaUtil, quartos, vagas,      bairro->{ _id, nome, slug, cidade, estado, mercado },    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {      asset->{ _id, url, metadata { lqip, dimensions } },      hotspot, crop, alt    }  }
export type IMOVEIS_DESTAQUE_QUERYResult = Array<{
  _id: string
  titulo: string | null
  slug: Slug | null
  tipo:
    | 'Apartamento'
    | 'Casa de Condom\xEDnio'
    | 'Casa'
    | 'Cobertura Duplex'
    | 'Cobertura'
    | 'Loja'
    | 'Penthouse'
    | 'Sala Comercial'
    | 'Terreno'
    | null
  finalidade: 'Loca\xE7\xE3o' | 'Temporada' | 'Venda' | null
  mercado: 'Canela' | 'Gramado' | 'Rio de Janeiro' | null
  preco: number | null
  areaUtil: number | null
  quartos: number | null
  vagas: number | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  imagemCapa: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: null
  } | null
}>
// Variable: IMOVEIS_POR_BAIRRO_QUERY
// Query: *[_type == "imovel" && bairro->slug.current == $bairroSlug && status == "Disponível"] | order(publicadoEm desc)[0...$limit] {    _id, titulo, slug, tipo, preco, areaUtil, quartos, vagas,      bairro->{ _id, nome, slug, cidade, estado, mercado },    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {      asset->{ _id, url, metadata { lqip, dimensions } },      hotspot, crop, alt    }  }
export type IMOVEIS_POR_BAIRRO_QUERYResult = Array<{
  _id: string
  titulo: string | null
  slug: Slug | null
  tipo:
    | 'Apartamento'
    | 'Casa de Condom\xEDnio'
    | 'Casa'
    | 'Cobertura Duplex'
    | 'Cobertura'
    | 'Loja'
    | 'Penthouse'
    | 'Sala Comercial'
    | 'Terreno'
    | null
  preco: number | null
  areaUtil: number | null
  quartos: number | null
  vagas: number | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  imagemCapa: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    alt: null
  } | null
}>
// Variable: BAIRROS_QUERY
// Query: *[_type == "bairro"] | order(ordem asc) {    _id, nome, slug, cidade, estado, mercado, regiao, ordem,    fotoCapa { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },    fotoAerea { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },    "totalImoveis": count(*[_type == "imovel" && bairro._ref == ^._id && status == "Disponível"])  }
export type BAIRROS_QUERYResult = Array<{
  _id: string
  nome: string | null
  slug: Slug | null
  cidade: string | null
  estado: 'RJ' | 'RS' | null
  mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  regiao: 'Canela' | 'Centro' | 'Gramado' | 'Sudoeste' | 'Zona Sul' | null
  ordem: number | null
  fotoCapa: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  fotoAerea: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  totalImoveis: number
}>
// Variable: BAIRRO_QUERY
// Query: *[_type == "bairro" && slug.current == $slug][0] {    _id, nome, slug, cidade, estado, mercado, regiao,    fotoCapa { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },    fotoAerea { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },    descricao, geo, pontosDeInteresse[] { nome, categoria, lat, lng },    "totalImoveis": count(*[_type == "imovel" && bairro._ref == ^._id && status == "Disponível"])  }
export type BAIRRO_QUERYResult = {
  _id: string
  nome: string | null
  slug: Slug | null
  cidade: string | null
  estado: 'RJ' | 'RS' | null
  mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  regiao: 'Canela' | 'Centro' | 'Gramado' | 'Sudoeste' | 'Zona Sul' | null
  fotoCapa: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  fotoAerea: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  descricao: string | null
  geo: {
    lat?: number
    lng?: number
  } | null
  pontosDeInteresse: Array<{
    nome: string | null
    categoria:
      | 'Academia'
      | 'Escola'
      | 'Hospital'
      | 'Metr\xF4'
      | 'Praia'
      | 'Restaurante'
      | 'Shopping'
      | 'Supermercado'
      | null
    lat: number | null
    lng: number | null
  }> | null
  totalImoveis: number
} | null
// Variable: CONDOMINIOS_QUERY
// Query: *[_type == "condominio"] | order(ordem asc) {    _id, nome, slug, tipo, destaque, descricao, infraestrutura, areaTotal, totalLotes,    bairro->{ _id, nome, slug, cidade, estado, mercado },    "fotoCapa": fotoCapa.asset->{ _id, url, metadata { lqip, dimensions } },    "totalImoveis": count(*[_type == "imovel" && condominioRef._ref == ^._id && status == "Disponível"])  }
export type CONDOMINIOS_QUERYResult = Array<{
  _id: string
  nome: string | null
  slug: Slug | null
  tipo: 'bairro-planejado' | 'condominio-fechado' | 'resort' | 'vertical' | null
  destaque: boolean | null
  descricao: string | null
  infraestrutura: Array<string> | null
  areaTotal: number | null
  totalLotes: number | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  fotoCapa: null
  totalImoveis: number
}>
// Variable: CONDOMINIOS_DESTAQUE_QUERY
// Query: *[_type == "condominio" && destaque == true] | order(ordem asc)[0...6] {    _id, nome, slug, tipo, descricao,    bairro->{ _id, nome, slug, cidade, estado, mercado },    "fotoCapa": fotoCapa.asset->{ _id, url, metadata { lqip, dimensions } },    "totalImoveis": count(*[_type == "imovel" && condominioRef._ref == ^._id && status == "Disponível"])  }
export type CONDOMINIOS_DESTAQUE_QUERYResult = Array<{
  _id: string
  nome: string | null
  slug: Slug | null
  tipo: 'bairro-planejado' | 'condominio-fechado' | 'resort' | 'vertical' | null
  descricao: string | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  fotoCapa: null
  totalImoveis: number
}>
// Variable: CONDOMINIO_QUERY
// Query: *[_type == "condominio" && slug.current == $slug][0] {    _id, nome, slug, tipo, descricao, infraestrutura, areaTotal, totalLotes,    bairro->{ _id, nome, slug, cidade, estado, mercado },    "fotoCapa": fotoCapa.asset->{ _id, url, metadata { lqip, dimensions } },    galeria[]{ asset->{ _id, url, metadata { lqip, dimensions } }, alt },    "totalImoveis": count(*[_type == "imovel" && condominioRef._ref == ^._id && status == "Disponível"])  }
export type CONDOMINIO_QUERYResult = {
  _id: string
  nome: string | null
  slug: Slug | null
  tipo: 'bairro-planejado' | 'condominio-fechado' | 'resort' | 'vertical' | null
  descricao: string | null
  infraestrutura: Array<string> | null
  areaTotal: number | null
  totalLotes: number | null
  bairro: {
    _id: string
    nome: string | null
    slug: Slug | null
    cidade: string | null
    estado: 'RJ' | 'RS' | null
    mercado: 'Rio de Janeiro' | 'Serra Ga\xFAcha' | null
  } | null
  fotoCapa: null
  galeria: Array<{
    asset: null
    alt: string | null
  }> | null
  totalImoveis: number
} | null
// Variable: CONDOMINIOS_SLUGS_QUERY
// Query: *[_type == "condominio" && defined(slug.current)] { "slug": slug.current }
export type CONDOMINIOS_SLUGS_QUERYResult = Array<{
  slug: string | null
}>
// Variable: IMOVEIS_SLUGS_QUERY
// Query: *[_type == "imovel" && defined(slug.current)] { "slug": slug.current }
export type IMOVEIS_SLUGS_QUERYResult = Array<{
  slug: string | null
}>
// Variable: BAIRROS_SLUGS_QUERY
// Query: *[_type == "bairro" && defined(slug.current)] { "slug": slug.current }
export type BAIRROS_SLUGS_QUERYResult = Array<{
  slug: string | null
}>
// Variable: BLOG_SLUGS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)] { "slug": slug.current }
export type BLOG_SLUGS_QUERYResult = Array<{
  slug: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  arquivo {\n    asset->{ _id, url, metadata { lqip, dimensions } },\n    hotspot, crop,\n    alt, principal, tour360, urlMatterport, isStaging, stagingPar\n  }\n': ImagemFragmentResult
    '\n  bairro->{ _id, nome, slug, cidade, estado, mercado }\n': BairroFragmentResult
    '\n  *[_type == "imovel" && status == "Dispon\xEDvel"] | order(publicadoEm desc) {\n    _id, titulo, slug, tipo, finalidade, mercado, status, destaque,\n    exclusivo, permuta, novidade, precoSobConsulta,\n    preco, areaUtil, quartos, suites, vagas, andar,\n    \n  bairro->{ _id, nome, slug, cidade, estado, mercado }\n,\n    "condominionome": condominioRef->nome,\n    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      hotspot, crop, alt\n    }\n  }\n': IMOVEIS_CARD_QUERYResult
    '\n  *[\n    _type == "imovel"\n    && status == "Dispon\xEDvel"\n    && ($tipo == "" || tipo == $tipo)\n    && ($mercado == "" || mercado == $mercado)\n    && ($finalidade == "" || finalidade == $finalidade)\n    && ($bairroSlug == "" || bairro->slug.current == $bairroSlug)\n    && ($precoMin == 0 || preco >= $precoMin)\n    && ($precoMax == 0 || preco <= $precoMax)\n    && ($quartos == 0 || quartos >= $quartos)\n  ] | order(publicadoEm desc) [$offset...$end] {\n    _id, titulo, slug, tipo, finalidade, mercado, status,\n    exclusivo, permuta, novidade, precoSobConsulta,\n    preco, areaUtil, quartos, suites, vagas, andar,\n    \n  bairro->{ _id, nome, slug, cidade, estado, mercado }\n,\n    "condominionome": condominioRef->nome,\n    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      hotspot, crop, alt\n    }\n  }\n': IMOVEIS_FILTRADOS_QUERYResult
    '\n  *[_type == "imovel" && slug.current == $slug][0] {\n    _id, titulo, slug, tipo, finalidade, mercado, status, destaque,\n    preco, condominio, iptu, areaUtil, areaTotal,\n    quartos, suites, banheiros, vagas, andar,\n    \n  bairro->{ _id, nome, slug, cidade, estado, mercado }\n,\n    endereco,\n    imagens[] { \n  arquivo {\n    asset->{ _id, url, metadata { lqip, dimensions } },\n    hotspot, crop,\n    alt, principal, tour360, urlMatterport, isStaging, stagingPar\n  }\n },\n    plantas[] {\n      arquivo { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },\n      titulo,\n      ambientes[] { nome, tipo, area, x, y }\n    },\n    caracteristicas[] { grupo, nome },\n    descricaoPtBr, descricaoEnUs, descricaoFrFr,\n    seo, publicadoEm\n  }\n': IMOVEL_PDI_QUERYResult
    '\n  *[_type == "imovel" && destaque == true && status == "Dispon\xEDvel"] | order(publicadoEm desc)[0...6] {\n    _id, titulo, slug, tipo, finalidade, mercado, preco, areaUtil, quartos, vagas,\n    \n  bairro->{ _id, nome, slug, cidade, estado, mercado }\n,\n    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      hotspot, crop, alt\n    }\n  }\n': IMOVEIS_DESTAQUE_QUERYResult
    '\n  *[_type == "imovel" && bairro->slug.current == $bairroSlug && status == "Dispon\xEDvel"] | order(publicadoEm desc)[0...$limit] {\n    _id, titulo, slug, tipo, preco, areaUtil, quartos, vagas,\n    \n  bairro->{ _id, nome, slug, cidade, estado, mercado }\n,\n    "imagemCapa": coalesce(imagens[arquivo.principal == true][0], imagens[0]).arquivo {\n      asset->{ _id, url, metadata { lqip, dimensions } },\n      hotspot, crop, alt\n    }\n  }\n': IMOVEIS_POR_BAIRRO_QUERYResult
    '\n  *[_type == "bairro"] | order(ordem asc) {\n    _id, nome, slug, cidade, estado, mercado, regiao, ordem,\n    fotoCapa { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },\n    fotoAerea { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },\n    "totalImoveis": count(*[_type == "imovel" && bairro._ref == ^._id && status == "Dispon\xEDvel"])\n  }\n': BAIRROS_QUERYResult
    '\n  *[_type == "bairro" && slug.current == $slug][0] {\n    _id, nome, slug, cidade, estado, mercado, regiao,\n    fotoCapa { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },\n    fotoAerea { asset->{ _id, url, metadata { lqip, dimensions } }, hotspot, crop },\n    descricao, geo, pontosDeInteresse[] { nome, categoria, lat, lng },\n    "totalImoveis": count(*[_type == "imovel" && bairro._ref == ^._id && status == "Dispon\xEDvel"])\n  }\n': BAIRRO_QUERYResult
    '\n  *[_type == "condominio"] | order(ordem asc) {\n    _id, nome, slug, tipo, destaque, descricao, infraestrutura, areaTotal, totalLotes,\n    bairro->{ _id, nome, slug, cidade, estado, mercado },\n    "fotoCapa": fotoCapa.asset->{ _id, url, metadata { lqip, dimensions } },\n    "totalImoveis": count(*[_type == "imovel" && condominioRef._ref == ^._id && status == "Dispon\xEDvel"])\n  }\n': CONDOMINIOS_QUERYResult
    '\n  *[_type == "condominio" && destaque == true] | order(ordem asc)[0...6] {\n    _id, nome, slug, tipo, descricao,\n    bairro->{ _id, nome, slug, cidade, estado, mercado },\n    "fotoCapa": fotoCapa.asset->{ _id, url, metadata { lqip, dimensions } },\n    "totalImoveis": count(*[_type == "imovel" && condominioRef._ref == ^._id && status == "Dispon\xEDvel"])\n  }\n': CONDOMINIOS_DESTAQUE_QUERYResult
    '\n  *[_type == "condominio" && slug.current == $slug][0] {\n    _id, nome, slug, tipo, descricao, infraestrutura, areaTotal, totalLotes,\n    bairro->{ _id, nome, slug, cidade, estado, mercado },\n    "fotoCapa": fotoCapa.asset->{ _id, url, metadata { lqip, dimensions } },\n    galeria[]{ asset->{ _id, url, metadata { lqip, dimensions } }, alt },\n    "totalImoveis": count(*[_type == "imovel" && condominioRef._ref == ^._id && status == "Dispon\xEDvel"])\n  }\n': CONDOMINIO_QUERYResult
    '\n  *[_type == "condominio" && defined(slug.current)] { "slug": slug.current }\n': CONDOMINIOS_SLUGS_QUERYResult
    '\n  *[_type == "imovel" && defined(slug.current)] { "slug": slug.current }\n': IMOVEIS_SLUGS_QUERYResult
    '\n  *[_type == "bairro" && defined(slug.current)] { "slug": slug.current }\n': BAIRROS_SLUGS_QUERYResult
    '\n  *[_type == "blogPost" && defined(slug.current)] { "slug": slug.current }\n': BLOG_SLUGS_QUERYResult
  }
}
