/**
 * seed-bairros.mjs
 * Popula o Sanity com todos os bairros da Admirata.
 * PRÉ-REQUISITO: SANITY_WRITE_TOKEN com permissão "Editor"
 *   1. https://www.sanity.io/manage → projeto gvf51tpc → API → Tokens
 *   2. SANITY_WRITE_TOKEN="seu-token" node scripts/seed-bairros.mjs
 * Idempotente: usa createOrReplace com _id determinístico.
 */
import { createClient } from '@sanity/client'

const TOKEN = process.env.SANITY_WRITE_TOKEN
if (!TOKEN) {
  console.error('\n❌ SANITY_WRITE_TOKEN não definido.')
  console.error('   Execute: SANITY_WRITE_TOKEN="seu-token" node scripts/seed-bairros.mjs\n')
  process.exit(1)
}

const client = createClient({
  projectId: 'gvf51tpc',
  dataset: 'production',
  apiVersion: '2024-06-01',
  token: TOKEN,
  useCdn: false,
})

const BAIRROS = [
  // RIO - CENTRO
  { _id:'bairro-centro-rio', nome:'Centro', slug:'centro-rio-de-janeiro', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:100, geo:{lat:-22.9068,lng:-43.1729}, descricao:'O Centro do Rio de Janeiro é o coração histórico e financeiro da cidade, palco de uma transformação imobiliária acelerada nas últimas décadas. A região concentra edifícios históricos tombados, lofts industriais convertidos e residenciais modernos voltados para o mercado de alto padrão. Com a revitalização do Porto Maravilha e da Zona Portuária, o Centro ganhou novos eixos de valorização que atraem compradores jovens e investidores atentos a ativos com forte potencial de crescimento.' },
  { _id:'bairro-lapa', nome:'Lapa', slug:'lapa', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:110, geo:{lat:-22.9149,lng:-43.1839}, descricao:'A Lapa é um dos bairros mais icônicos do Rio de Janeiro, famosa pelos Arcos da Lapa e pela cena cultural boêmia que convive com um mercado imobiliário em plena requalificação. Edifícios históricos são convertidos em residenciais modernos e lofts de alto padrão, atraindo profissionais criativos e investidores que enxergam no patrimônio arquitetônico um diferencial único.' },
  { _id:'bairro-santa-teresa', nome:'Santa Teresa', slug:'santa-teresa', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:120, geo:{lat:-22.9192,lng:-43.1880}, descricao:'Santa Teresa é o bairro mais charmoso do Rio de Janeiro — um mosaico de casarões coloniais, ateliês de artistas e restaurantes premiados embrenhados nas encostas do morro com vista panorâmica para a Baía de Guanabara. O mercado imobiliário de Santa Teresa é único: propriedades com arquitetura histórica preservada, jardins exuberantes e vistas deslumbrantes alcançam valores que refletem a raridade dessas características.' },
  { _id:'bairro-gloria', nome:'Glória', slug:'gloria', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:130, geo:{lat:-22.9263,lng:-43.1780}, descricao:'A Glória é um bairro de transição entre o Centro histórico e a Zona Sul do Rio de Janeiro, com vista para a Baía de Guanabara e acesso privilegiado ao Parque do Flamengo. Residenciais com metragem generosa e acabamento de alto padrão convivem com o patrimônio histórico da Igreja de Nossa Senhora da Glória do Outeiro.' },
  { _id:'bairro-cidade-nova', nome:'Cidade Nova', slug:'cidade-nova', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:140, geo:{lat:-22.9117,lng:-43.1943}, descricao:'A Cidade Nova é um dos bairros mais bem localizados do Rio de Janeiro, fazendo fronteira com o Sambódromo e conectada diretamente ao Centro pela Linha Vermelha. Nos últimos anos, a região passou por forte valorização impulsionada pela proximidade com o Porto Maravilha.' },
  { _id:'bairro-catumbi', nome:'Catumbi', slug:'catumbi', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:150, geo:{lat:-22.9213,lng:-43.1946}, descricao:'O Catumbi é um bairro residencial tranquilo no coração do Rio de Janeiro, vizinho ao Centro e ao Rio Comprido, com características de bairro tradicional carioca. Com calçadas arborizadas, praças e comércio local diversificado, o Catumbi oferece qualidade de vida a poucos minutos do centro financeiro.' },
  { _id:'bairro-estacio', nome:'Estácio', slug:'estacio', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Centro', ordem:160, geo:{lat:-22.9139,lng:-43.1993}, descricao:'O Estácio é um bairro de tradição e identidade própria no centro do Rio de Janeiro, berço do samba carioca. Com forte polo universitário e médico, o bairro atrai demanda contínua por imóveis compactos e de médio padrão, especialmente voltados para locação.' },

  // RIO - ZONA SUL
  { _id:'bairro-flamengo', nome:'Flamengo', slug:'flamengo', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:200, geo:{lat:-22.9316,lng:-43.1736}, descricao:'O Flamengo é um dos bairros mais tradicionais da Zona Sul do Rio de Janeiro, com amplos calçadões à beira do Parque do Flamengo, vista para a Baía de Guanabara e o Pão de Açúcar. Residenciais clássicos convivem com empreendimentos modernos de alto padrão que valorizam a localização privilegiada.' },
  { _id:'bairro-botafogo', nome:'Botafogo', slug:'botafogo', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:210, geo:{lat:-22.9424,lng:-43.1850}, descricao:'Botafogo é o bairro mais dinâmico da Zona Sul do Rio de Janeiro — um ponto de encontro entre a Praia de Botafogo, o Parque do Flamengo e a Enseada de Botafogo com vista direta para o Pão de Açúcar. O mercado imobiliário de Botafogo é um dos mais valorizados da cidade, com apartamentos de alto padrão e coberturas com vistas inesquecíveis.' },
  { _id:'bairro-humaita', nome:'Humaitá', slug:'humaita', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:220, geo:{lat:-22.9490,lng:-43.1877}, descricao:'O Humaitá é um bairro residencial de alto padrão encravado entre Botafogo, Laranjeiras e o Jardim Botânico, com ruas arborizadas e atmosfera tranquila. O bairro concentra residenciais de alto padrão com metragens generosas, muitos com vista para o Cristo Redentor.' },
  { _id:'bairro-laranjeiras', nome:'Laranjeiras', slug:'laranjeiras', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:230, geo:{lat:-22.9374,lng:-43.1930}, descricao:'Laranjeiras é um bairro de charme e sofisticação discreta na Zona Sul do Rio, conhecido pelas ruas sinuosas flanqueadas por árvores centenárias e pelos palacetes do início do século XX. O bairro abriga algumas das propriedades históricas mais desejadas da cidade.' },
  { _id:'bairro-catete', nome:'Catete', slug:'catete', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:240, geo:{lat:-22.9288,lng:-43.1803}, descricao:'O Catete é um bairro histórico da Zona Sul do Rio de Janeiro, sede do antigo Palácio do Catete (hoje Museu da República). Com estação de metrô própria e fácil acesso ao Flamengo e à Glória, o Catete oferece boa conectividade e serviços consolidados.' },
  { _id:'bairro-cosme-velho', nome:'Cosme Velho', slug:'cosme-velho', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:250, geo:{lat:-22.9410,lng:-43.1934}, descricao:'O Cosme Velho é um dos bairros mais exclusivos e tranquilos do Rio de Janeiro — ao pé do Corcovado e com acesso ao trem do Cristo Redentor. Rodeado pela Mata Atlântica, o bairro oferece casas históricas e residenciais de alto padrão com jardins exuberantes e privacidade incomparável.' },
  { _id:'bairro-urca', nome:'Urca', slug:'urca', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:260, geo:{lat:-22.9529,lng:-43.1663}, descricao:'A Urca é, sem dúvida, o bairro mais exclusivo do Rio de Janeiro. Vizinha ao Pão de Açúcar, a Urca é uma pequena península com apenas algumas ruas, casas históricas e uma praia tranquila. O número de imóveis disponíveis é extremamente limitado — o que garante valorização consistente e liquidez privilegiada.' },
  { _id:'bairro-copacabana', nome:'Copacabana', slug:'copacabana', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:270, geo:{lat:-22.9658,lng:-43.1741}, descricao:'Copacabana é a praia mais famosa do mundo e um dos maiores polos imobiliários do Rio de Janeiro. Com 4 km de extensão, a orla concentra alguns dos apartamentos e coberturas mais valorizados da Zona Sul. Para investidores, Copacabana oferece alta liquidez e retorno consistente com aluguel por temporada.' },
  { _id:'bairro-leme', nome:'Leme', slug:'leme', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:280, geo:{lat:-22.9612,lng:-43.1667}, descricao:'O Leme é o extremo norte da orla de Copacabana — um bairro com vista privilegiada para o Morro do Leme e a Praia Vermelha, menos movimentado que Copacabana e com características mais residenciais. Coberturas frente ao mar são especialmente valorizadas pela combinação de privacidade e vista panorâmica.' },
  { _id:'bairro-ipanema', nome:'Ipanema', slug:'ipanema', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:290, geo:{lat:-22.9868,lng:-43.1953}, descricao:'Ipanema é o símbolo da Zona Sul do Rio de Janeiro — uma praia dourada, ruas elegantes e um mercado imobiliário entre os mais valorizados da cidade. Apartamentos e coberturas de frente para o mar, especialmente com vista para o Morro Dois Irmãos, estão entre os imóveis mais disputados do Brasil.' },
  { _id:'bairro-leblon', nome:'Leblon', slug:'leblon', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:300, geo:{lat:-22.9840,lng:-43.2219}, descricao:'O Leblon é o bairro mais valorizado do Brasil — e um dos mais exclusivos da América Latina. Limitado pela Lagoa Rodrigo de Freitas, pelo Morro Dois Irmãos e pelo mar, o Leblon oferece uma qualidade de vida incomparável com privacidade, segurança e serviços de alto padrão. O metro quadrado do Leblon é consistentemente o mais alto do Rio de Janeiro.' },
  { _id:'bairro-lagoa', nome:'Lagoa', slug:'lagoa', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:310, geo:{lat:-22.9726,lng:-43.2042}, descricao:'O bairro da Lagoa é construído em torno da belíssima Lagoa Rodrigo de Freitas. Com a pista de corrida, restaurantes flutuantes e as melhores academias ao ar livre da cidade, o bairro oferece um estilo de vida ativo e sofisticado com residenciais de alto padrão e vistas privilegiadas.' },
  { _id:'bairro-jardim-botanico', nome:'Jardim Botânico', slug:'jardim-botanico', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:320, geo:{lat:-22.9665,lng:-43.2221}, descricao:'O Jardim Botânico é um dos bairros mais elegantes e tranquilos da Zona Sul do Rio de Janeiro, vizinho ao mundialmente famoso Jardim Botânico do Rio e ao Parque Lage. Ruas arborizadas, restaurantes conceituados e residenciais de alto padrão definem um bairro que atrai famílias exigentes.' },
  { _id:'bairro-gavea', nome:'Gávea', slug:'gavea', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:330, geo:{lat:-22.9868,lng:-43.2381}, descricao:'A Gávea é um bairro universitário e residencial de prestígio, lar da PUC-Rio e do Instituto Moreira Salles. Casas e mansões cercadas pela Mata Atlântica convivem com residenciais modernos de alto padrão e uma gastronomia premiada no Baixo Gávea.' },
  { _id:'bairro-vidigal', nome:'Vidigal', slug:'vidigal', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:340, geo:{lat:-22.9975,lng:-43.2268}, descricao:'O Vidigal é um dos bairros com o cenário mais deslumbrante do Rio de Janeiro — situado entre o Leblon e São Conrado, nas encostas com vista panorâmica para o Morro Dois Irmãos, a Praia do Leblon e o mar aberto.' },
  { _id:'bairro-sao-conrado', nome:'São Conrado', slug:'sao-conrado', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Zona Sul', ordem:350, geo:{lat:-23.0151,lng:-43.2721}, descricao:'São Conrado é um enclave de luxo entre o Vidigal, a Floresta da Tijuca e o Oceano Atlântico — um bairro com praias praticamente particulares, condomínios fechados de alto padrão e o icônico Fashion Mall.' },

  // RIO - SUDOESTE
  { _id:'bairro-barra-da-tijuca', nome:'Barra da Tijuca', slug:'barra-da-tijuca', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Sudoeste', ordem:400, geo:{lat:-23.0014,lng:-43.3659}, descricao:'A Barra da Tijuca é o maior polo de imóveis de luxo e alto padrão do Rio de Janeiro — uma cidade planejada com 18 km de praia, condomínios fechados de padrão internacional, shoppings premium e uma oferta gastronômica incomparável. Para a Admirata, é o principal mercado de atuação no segmento de alto padrão no Rio de Janeiro.' },
  { _id:'bairro-recreio-dos-bandeirantes', nome:'Recreio dos Bandeirantes', slug:'recreio-dos-bandeirantes', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Sudoeste', ordem:410, geo:{lat:-23.0201,lng:-43.4734}, descricao:'O Recreio dos Bandeirantes é a extensão natural e mais tranquila da Barra da Tijuca — um bairro com 6 km de praias menos movimentadas, condomínios fechados com amplos espaços verdes e uma qualidade de vida incomparável para famílias.' },
  { _id:'bairro-jacarepagua', nome:'Jacarepaguá', slug:'jacarepagua', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Sudoeste', ordem:420, geo:{lat:-22.9640,lng:-43.3540}, descricao:'Jacarepaguá é uma vasta região em plena transformação urbana, com bairros nobres como o Itanhangá e o Joá entre os mais exclusivos da cidade. A lagoa de Jacarepaguá e os condomínios fechados configuram um mercado imobiliário diversificado.' },
  { _id:'bairro-itanhanga', nome:'Itanhangá', slug:'itanhanga', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Sudoeste', ordem:430, geo:{lat:-23.0062,lng:-43.3214}, descricao:'O Itanhangá é um dos bairros mais exclusivos da Zona Oeste do Rio de Janeiro — um enclave residencial de altíssimo padrão entre a Pedra da Gávea, o Golf Course do Itanhangá e a Barra da Tijuca. A raridade de imóveis disponíveis garante valorização consistente.' },
  { _id:'bairro-joa', nome:'Joá', slug:'joa', cidade:'Rio de Janeiro', estado:'RJ', mercado:'Rio de Janeiro', regiao:'Sudoeste', ordem:440, geo:{lat:-23.0186,lng:-43.3025}, descricao:'O Joá é um dos bairros mais cobiçados e exclusivos do Rio de Janeiro — situado entre o mar, a Pedra da Gávea e a Floresta da Tijuca, com acesso controlado e um número extremamente limitado de imóveis disponíveis. Propriedades no Joá são referência de luxo absoluto.' },

  // GRAMADO
  { _id:'bairro-centro-gramado', nome:'Centro', slug:'centro-gramado', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:100, geo:{lat:-29.3783,lng:-50.8768}, descricao:'O Centro de Gramado é o coração de uma das cidades mais charmosas do Brasil — uma vila europeia encravada na Serra Gaúcha com arquitetura enxaimel, flores nas sacadas e um clima de montanha que encanta turistas e residentes o ano inteiro. Para investidores, é uma das localizações com melhor rentabilidade em hospedagem por temporada em todo o Sul do Brasil.' },
  { _id:'bairro-planalto-gramado', nome:'Planalto', slug:'planalto-gramado', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:110, geo:{lat:-29.3900,lng:-50.8900}, descricao:'O bairro Planalto é um dos mais residenciais e tranquilos de Gramado, com loteamentos de alto padrão, casas enxaimel e amplos jardins que refletem o estilo de vida da Serra Gaúcha. A altitude elevada garante vista panorâmica para as montanhas cobertas pela Mata Atlântica.' },
  { _id:'bairro-piratini', nome:'Piratini', slug:'piratini', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:120, geo:{lat:-29.3700,lng:-50.8700}, descricao:'O bairro Piratini em Gramado combina proximidade ao Centro com características residenciais mais tranquilas, ideal para quem busca a qualidade de vida da Serra Gaúcha. Casas e condomínios de médio e alto padrão, com arquitetura típica germânica, formam o perfil imobiliário do bairro.' },
  { _id:'bairro-carniel', nome:'Carniel', slug:'carniel', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:130, geo:{lat:-29.3600,lng:-50.8800}, descricao:'O bairro Carniel é uma das áreas mais bucólicas de Gramado, com caminhos rurais, pomares e uma paisagem que parece saída de uma pintura alpina. Chácaras, casas rurais e loteamentos de alto padrão com terrenos amplos são as principais opções do mercado local.' },
  { _id:'bairro-sao-francisco-gramado', nome:'São Francisco', slug:'sao-francisco-gramado', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:140, geo:{lat:-29.3650,lng:-50.8650}, descricao:'O bairro São Francisco é um dos mais valorizados de Gramado para quem busca imóveis com amplos terrenos, vista para as montanhas e facilidade de acesso ao Centro. Com ruas arborizadas e condomínios de alto padrão, o São Francisco atrai compradores que desejam residir na Serra Gaúcha com conforto.' },
  { _id:'bairro-riedlinger', nome:'Riedlinger', slug:'riedlinger', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:150, geo:{lat:-29.3850,lng:-50.8950}, descricao:'O bairro Riedlinger preserva a mais genuína atmosfera colonial europeia de Gramado — casas em enxaimel original, jardins floridos e ruas de paralelepípedo que remetem às origens alemãs da cidade.' },
  { _id:'bairro-carazal', nome:'Carazal', slug:'carazal', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:160, geo:{lat:-29.4000,lng:-50.8600}, descricao:'O Carazal é um bairro às margens da cidade de Gramado, com caráter rural e paisagem aberta que valoriza os grandes terrenos. A região é procurada para construção de chalés de alto padrão para temporada e investimentos em glamping.' },
  { _id:'bairro-floresta-gramado', nome:'Floresta', slug:'floresta-gramado', cidade:'Gramado', estado:'RS', mercado:'Serra Gaúcha', regiao:'Gramado', ordem:170, geo:{lat:-29.3720,lng:-50.8820}, descricao:'O bairro Floresta em Gramado é exatamente o que o nome promete: imóveis entre árvores nativas da Mata Atlântica, trilhas ecológicas e uma biodiversidade que encanta. Chalés de alto padrão e pequenos condomínios imersos no verde são muito procurados para hospedagem turística premium.' },

  // CANELA
  { _id:'bairro-centro-canela', nome:'Centro', slug:'centro-canela', cidade:'Canela', estado:'RS', mercado:'Serra Gaúcha', regiao:'Canela', ordem:200, geo:{lat:-29.3633,lng:-50.8127}, descricao:'O Centro de Canela é o coração de uma das cidades mais encantadoras da Serra Gaúcha — a poucos minutos de Gramado e com uma identidade própria que mistura aventura, natureza e gastronomia de montanha. A Catedral de Pedra e o Parque do Caracol são os principais cartões-postais.' },
  { _id:'bairro-caracol', nome:'Caracol', slug:'caracol', cidade:'Canela', estado:'RS', mercado:'Serra Gaúcha', regiao:'Canela', ordem:210, geo:{lat:-29.3100,lng:-50.8500}, descricao:'O bairro Caracol em Canela é um dos mais exclusivos da Serra Gaúcha — localizado às bordas do Parque do Caracol, com a famosa Cascata do Caracol a poucos metros de algumas propriedades. Chalés premium e pousadas boutique imersos na floresta atraem compradores em busca de alta rentabilidade turística.' },
  { _id:'bairro-petropolis-canela', nome:'Petrópolis', slug:'petropolis-canela', cidade:'Canela', estado:'RS', mercado:'Serra Gaúcha', regiao:'Canela', ordem:220, geo:{lat:-29.3700,lng:-50.8200}, descricao:'O bairro Petrópolis em Canela é uma área residencial de alto padrão com ruas tranquilas, arquitetura enxaimel bem conservada e uma qualidade de vida que remete às cidades europeias de montanha.' },
  { _id:'bairro-vila-suzana', nome:'Vila Suzana', slug:'vila-suzana', cidade:'Canela', estado:'RS', mercado:'Serra Gaúcha', regiao:'Canela', ordem:230, geo:{lat:-29.3750,lng:-50.8050}, descricao:'A Vila Suzana é um bairro residencial em expansão em Canela, com loteamentos de médio e alto padrão. O fácil acesso ao Centro de Canela e a Gramado faz da Vila Suzana uma opção estratégica para quem planeja construir sua residência de montanha com projeto personalizado.' },
  { _id:'bairro-vale-das-hortencias', nome:'Vale das Hortências', slug:'vale-das-hortencias', cidade:'Canela', estado:'RS', mercado:'Serra Gaúcha', regiao:'Canela', ordem:240, geo:{lat:-29.3800,lng:-50.8150}, descricao:'O Vale das Hortências é um dos endereços mais floridos e pitorescos da Serra Gaúcha — um bairro que leva o nome das hortênsias que cobrem jardins e calçadas em tons de azul, lilás e branco durante a primavera.' },
]

async function seed() {
  console.log(`\n🏙  Admirata — seed de bairros`)
  console.log(`📋 Total: ${BAIRROS.length} bairros\n`)

  const transaction = client.transaction()
  for (const bairro of BAIRROS) {
    const { _id, slug, geo, ...resto } = bairro
    const doc = { _id, _type:'bairro', ...resto, slug:{_type:'slug', current:slug}, ...(geo ? {geo} : {}) }
    transaction.createOrReplace(doc)
  }

  try {
    const result = await transaction.commit()
    console.log(`✅ ${result.results.length} documentos criados/atualizados!\n`)
    const porRegiao = {}
    BAIRROS.forEach(b => { const k=`${b.mercado} › ${b.regiao}`; porRegiao[k]=(porRegiao[k]||0)+1 })
    Object.entries(porRegiao).sort(([a],[b])=>a.localeCompare(b)).forEach(([k,n])=>console.log(`  ${k}: ${n}`))
    console.log('\n💡 Acesse /studio → Bairros para adicionar fotos de capa.\n')
  } catch(err) {
    console.error('\n❌ Erro:', err.message)
    if (err.statusCode===401) console.error('   Token inválido. Gere em: https://www.sanity.io/manage\n')
    process.exit(1)
  }
}

seed()
